function indiceseigenscape7819 = importIndices(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INDICESEIGENSCAPE7819 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  INDICESEIGENSCAPE7819 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  indiceseigenscape7819 = importfile("/Users/simon/gits/EigenScape/indices_eigenscape_7_8_19.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Aug-2019 14:14:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["filename", "Acoustic_Complexity_Index__main_value", "Acoustic_Complexity_Index__min", "Acoustic_Complexity_Index__max", "Acoustic_Complexity_Index__mean", "Acoustic_Complexity_Index__median", "Acoustic_Complexity_Index__std", "Acoustic_Complexity_Index__var", "Acoustic_Diversity_Index__main_value", "Acoustic_Evenness_Index__main_value", "Bio_acoustic_Index__main_value", "Normalized_Difference_Sound_Index__main_value", "RMS_energy__min", "RMS_energy__max", "RMS_energy__mean", "RMS_energy__median", "RMS_energy__std", "RMS_energy__var", "Spectral_Entropy__main_value", "Temporal_Entropy__main_value"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
indiceseigenscape7819 = readtable(filename, opts);

end